"""Clarte360 PIP RIASEC application package."""

from .version import APP_VERSION, BUILD_INCREMENT, FRAMEWORK_VERSION, PRODUCT_VERSION

__all__ = ["APP_VERSION", "PRODUCT_VERSION", "BUILD_INCREMENT", "FRAMEWORK_VERSION"]
