APP_VERSION = "1.0.10-l1-vps-hub-ready-guard-accompagnement"
PRODUCT_VERSION = "PIP-RIASEC-ONET-L1"
BUILD_INCREMENT = "L1-H1-RAPPORT-PUBLIC-SYNTHESE"
FRAMEWORK_VERSION = "4.0"
FRAMEWORK_VPS_VERSION = "1.0"

JALON_ID = "H1"
PIP_BANK_VERSION = "PIP-BANK-0.5"
PIP_MASTER_VERSION = "0.6"

PIP_INTERPRETATION_VERSION = "PIP-INT-1.0"
