[email]
smtp_server = "ssl0.ovh.net"
smtp_port = "465"
smtp_user = "contact@clarte360.com"
smtp_password = "votre_mot_de_passe"
from_email = "contact@clarte360.com"
to_email = "contact@clarte360.com"
